language: scala
jdk:
- oraclejdk8
env:
  global:
  - secure: gTRfQzAZhGkfICzaNoNUU9Y/cYPN525z15/7DR4vWof4fUGqC0F3sBa7x1m8qhxby/IomxQyfu7uMruMQquKhdtW1v0Ae7LtUgUcUDqMUwqdZFkkWGEs3LL8lx+O+yFhdIQ5gndMhQZrGp2N1JrQvLknCjTXwtG1Qc+KMz5URkMzcGxbJ9foYo8fC4RJ2k9UodT/V3YbeKvtsCZmzvsPNLgnnCYm9lKY/uTY2TkDaeB4XTwsps8yW87rggsnBGaKl2LTKQpCNbCfTukhHtjVKbwBlUV6n4abwystYcmkviOw2EL6wsjNYrXuNrg7ffM/AC5fSzPY2h6EJ2spSueXLn1SOcaCLA+mUlYIPylEn8I7nnVCkZlb4u6mF2fBKSXoL9J6mhzvJCw6RLQMJv5G+Gm+I3gL6O0RoSY8LqWNSqjE69rmZedy9o4ryrl91PmRF/JRzkF9RK4knPVw5MjA2Knu4UHdW8ScNUdXUVxodObVpEBOXDHxyaPXZiYgAgrnIy+lT4pkvO9xq1mtxPRc6mXIO9mI5e5fMTD8ZuAoUfQ9Z+e9bv0OrmK6rSpP59A1+dqfpUGvhc19ei9Xzk2uDqRK9wfcHLkfmVAhjt+xGUcrn9lKreNrT7i+qijg7czHb/7adVJNtb4SWKIiJqwBalxmImgwaug0Ro8OvoeIRzo=
  - secure: ou89tFT/Y5NqelKPRkga7cGNztlBxXySVnX37xd4rTTRxf0qUqrnVdfZ1IV27j2r/ci05fNg2ocPuTKaz/q0I84M1ha/0IG8SEtTEQptjPtqoH1OI1pTA7WOm8uaKRUewKruSL/SuUwKmw5pOQUhCU1g9eHgRCN/yoPE8J2y+tmALNJiAvYsJ+4Xu8kZubNv0D37Yor8zWbxnj02RvpJ/BkwEQAWGf6/UkDYt3ZtOnD76m5xJ0ZoYkLpHyT9LbKj6rRioARrteK9EnBK7xyfH2i2gOj/tx4ZLI3nY3hyES84u4OcsHPSfEW6jd+dSERQty000rsbi9DaoMmHPfwxi4By9S5S7ZTwsDM+BPhR/iyiYi/o1zqG7Y34EADYi+vua0iWRT21hqwVtZCPj1jq6kerETA2zXymNLdP/PGgu3OUR5xslYARKwfj8BABBx9JxuKgvtDMdhdLWwQxrubs+QVuGpX47eACFwWNl/U3Z4duKW0GGde2cKegDXpir+NKqB1/tqIhukzv1IXoCKecj32uhZbuHc9pJNFCwWSxyvLBKz5R62jbR2AYcz0j019p5ORJ/O0uPuA2UzRrIjfXrgbxNLatJV3LuEmeH5DSO86fvw/XDlJDudFcROeb1Akw8gOqX+BctKsQ3NAkGBeEekjpOnLsdlnbD4BO3gvjfWA=
before_script:
- mkdir ~/.bintray
- touch ~/.bintray/.credentials
- echo 'realm = Bintray API Realm'  >> ~/.bintray/.credentials
- echo 'host = api.bintray.com'     >> ~/.bintray/.credentials
- echo "user = $BT_USER"            >> ~/.bintray/.credentials
- echo "password = $BT_KEY"         >> ~/.bintray/.credentials
script:
- sbt +test && sbt +publish
cache:
  directories:
  - "$HOME/.ivy2"
  - "$HOME/.sbt"
