language: scala
jdk:
- oraclejdk8
env:
  global:
  - secure: P64oaFDWoJQVdq1WqJEbTvD2Qp2FJ9GSwIu0Vhw/qPv2vNmle79vC1Qksd7WyNgDLzwI0X4aqxoh4tLQVyp4JXGFDQU7RVqN9BHQt9eewWGo64sgGF7zc2T5NhI2WJNfPFStBO4cqukLwGXsvAs+twfuYgEFkkLhDt0Cs7WN1P4vvNTdMOcDmQzYb9YSNDrrPkh3G1B37z/FCv4g3Lgy0MTdmAvZxt7Zq33nstrSKP+HNXHnjWRxQqrRj4FKzGOG7UBLLH2jL8W5RI2d0s8nBplL2z902q66k4dQMs+RWMmgO2hWoMWycIz1Sdldk0uYNdP5IPQAnCG/pcyvx0k/G8vAtQkg6gvVnWkyI6a6yN0FZwRZnasNAiwzHE6ky1J/6ewawlA10IwfadP9bf0RR8DEZdgzRM5tDPJXs6dUDs/Sbz61D1F8qVQZ0fKBNMBQ8G87eCIReWInNMGAOKXX5P4bhkZnD+OsoEexXNQctVw2x6K+o7KgDKuGShcygiXmDSgJBAB1iyGPzAHj9kTlTFlTeEJSysB4YD2mS1jMBXrZRcKtX0Aq5AHyS+Jk/kS9n5pNP6Noy/huMEllK35wQoGLkrGP+J/bVObnw4INTP+73t1TcZm4Oth3vRPZV8ITVlhJtoURoS2EMLclQLrAJXslj/8bAxy48d9AW2l6+mU=
  - secure: XVrn0+0t8JVNSrxddnuj1Opjai/6zKgGvUW8HfZsF9XR7jHtUN+A9n1H7E//5K8FeKpyygE8/EPzX6LYG86/cF5I+ZxqIuL5VQFD0MTn2hqOAF6IXUrCUPzKx7RbhXSwtSqFr+HnrgjDR0YBJjteaTXhFmBDCnvLuSyPLdi0wJ6xswAv1w+dq1aPDMGKy0cM/NQ01PUzFxfhk4aR9v3yyHaKoaJBiT+TL9FrvbE/p886qU8FG1fH99mHita/kRa6nxruDlUZ4e3ZqPuMvT6NegLKAj4dM7tuUPidJEo6hqZ3RZNSEMhtlc89AvjFY60JxeGmHYw4WvX9ynvo4HWXVmCDv+WTnBmBm7PPh+FOHihzvsCLknpCOxBpTMQiE8lZ2uGHoyg+kHB5ft6sBEEsmWOwb47JD96i2O/obAzfPEVl8iTwp0N4mfuUSoSEV6p4Tp5dAh+SApsqWYfax0Gzy7zAJykEy++ridJ8uR8NHSQpiiVFcm12RsCQ8qWjq5Y3x0nkrK99k6vV3FIDjeySeMtZa3H0QG8/+ophMB16BoZ6vR5tI+rmYX+qsq3bhxEVHvYUOWGorvV0TL2pLNsH/FJx3UjUtysFw9cV4sTKslttq9gtcyLcjX/uanRlvYVFl0w5QBL9I+2UtP0rRmZcQk3c+Vo9uiYD3IWumJxZkCM=
before_script:
- mkdir ~/.bintray
- touch ~/.bintray/.credentials
- echo 'realm = Bintray API Realm'  >> ~/.bintray/.credentials
- echo 'host = api.bintray.com'     >> ~/.bintray/.credentials
- echo "user = $BT_USER"            >> ~/.bintray/.credentials
- echo "password = $BT_KEY"         >> ~/.bintray/.credentials
script:
- sbt +test && sbt +publish
cache:
  directories:
  - "$HOME/.ivy2"
  - "$HOME/.sbt"
