language: scala
jdk:
- oraclejdk8
env:
  global:
  - secure: RGiEqODinFmYw8cRn4eCb8D1TleeeS8h3Mw0GY01wFzMVjgT8r/Gd1V7i6M1stpaiEyiaNWMUfu277Nix7P60zBU7/enXo/QUsq7avpF2GLpKwkLam6nItFglMnNaxK/qoCK8UrUgi/JIuK2gmtwKm9JCzh0g/AoLbmxKjNpTjAl06UjuJPw9Drs7NuGmI3zRhH0txWGjW6vz7u59tiB1wc2r6ZvZTBH7l9YKTEJjMQ4rbqh+FDv+wBqWIqu5Xhwg73Sg3npVHjEDBM8xEpPoTMsnaz3escEpolkme2TT2/cNcJ3ZCs5JvMHO95ujYxgTuf8BheSyI7uVD8wmoSmFoIXBhQtWnFOXrkmZvtMdOGtGIxb+bCzAETy5TDSijKxWjM6IRHR8eSOVCxGGMrvRSbBHREVRtlA8FQZyGVadYPZQ5DfU7DamLfzm3FMFnwU9+qizuNLqFUj1ZGzANnJHeFiNnOxJ8VDT7W06NtGMLfCJiiH/D9GdrvQlY5pjmTsJsoz28OjC3F/2G2ZNmU/ywTpqFhRHUs9dzE8jx1qoUFPDxBIUzYdIn8/9P/7SyNigeofTRhuLq8NHrJyy2QAEvBmJYZK1MkO431SsfJL7u5P2CGeGmwv0Em6Wz9OdLvp2s+S+vqL0mTm7A3YjrmQyE/0zPaKsTM9YjiQp/SzSDI=
  - secure: hKqigay3PEgRGaJkf8NYqSs60YqRSdfU8P3x5HQ/ojBeMZ9pyNgaB5NA1YwQXBvNkOFhAYhdIIDTtoxnO+o1IxrLcn5PZkizvIPbZGG1Z7sLsGPhviIVv3yPArNz7IcZfcv+yhFMKPO9xRu1pvZRtVpU2YXoGcPhvqMq3FqnDQy8yI5dgzkzamsXMSrcgKGnwsXzD0QA/7h+E4gFkeInJMF7lvlrDga2GHku4PdV6yptjcvvRrG4v3d0cJfD7Q7/NeZjyFRoH4ejOZ6Govya0+3H6/2nazxNEzbjGHJaQa/qowVwfL0tlSf9JokzjcYOKTb7U5/CkueHVw25gj1Dd6boauLY8yhWlKDb5P0/WpB9T06aMjaCtya6DyIopOyhY6jd6i1XpO62budt1ZCFZASiNvd+bBd4HK1raWxfS5w2RZg7+7H1Du2xJ+o/0W5v5/gNILWks0wrE7H+VRY5JrdeFqqRzET/K3mvRYlfnzXZPqdf7ctrjLs5vuo5mZ6yoyk0QqxXb+MBEHT9clmW+Y6uQidFS2UY06IKeKsY+Wl27Yg96yHTletlPed7W5gMOw0vhrSCyOut1yXIb6352SHtwoGoaw+ItR+//IvQGU0Al7HZ0j1i7gKLZmm4Ev+qYEVky7SGMYaOrCAOm8/WI/7TvFCy8pBVqP/DdfRE8K8=
before_script:
- mkdir ~/.bintray
- touch ~/.bintray/.credentials
- echo 'realm = Bintray API Realm'  >> ~/.bintray/.credentials
- echo 'host = api.bintray.com'     >> ~/.bintray/.credentials
- echo "user = $BT_USER"            >> ~/.bintray/.credentials
- echo "password = $BT_KEY"         >> ~/.bintray/.credentials
script:
- sbt +test && sbt +publish
cache:
  directories:
  - "$HOME/.ivy2"
  - "$HOME/.sbt"
